/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../../index.js";

/**
 * @example
 *     {
 *         userName: "userName",
 *         name: {
 *             formatted: undefined
 *         },
 *         emails: undefined,
 *         active: undefined,
 *         password: undefined
 *     }
 */
export interface CreateUserRequest {
  /** User's email address (required) */
  userName: string;
  /** User's name information */
  name: AgentInsightAPI.ScimName;
  /** User's email addresses */
  emails?: AgentInsightAPI.ScimEmail[];
  /** Whether the user is active */
  active?: boolean;
  /** Initial password for the user */
  password?: string;
}
