/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface PaginatedLlmConnections {
  data: AgentInsightAPI.LlmConnection[];
  meta: AgentInsightAPI.utils.MetaResponse;
}
