/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface PaginatedSessions {
  data: AgentInsightAPI.Session[];
  meta: AgentInsightAPI.utils.MetaResponse;
}
