/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface AnnotationQueueItem {
  id: string;
  queueId: string;
  objectId: string;
  objectType: AgentInsightAPI.AnnotationQueueObjectType;
  status: AgentInsightAPI.AnnotationQueueStatus;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}
