/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface CreateAnnotationQueueItemRequest {
  objectId: string;
  objectType: AgentInsightAPI.AnnotationQueueObjectType;
  /** Defaults to PENDING for new queue items */
  status?: AgentInsightAPI.AnnotationQueueStatus;
}
