/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface PaginatedAnnotationQueues {
  data: AgentInsightAPI.AnnotationQueue[];
  meta: AgentInsightAPI.utils.MetaResponse;
}
