/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface SchemaResource {
  id: string;
  name: string;
  description: string;
  attributes: unknown[];
  meta: AgentInsightAPI.ResourceMeta;
}
