/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface ServiceProviderConfig {
  schemas: string[];
  documentationUri: string;
  patch: AgentInsightAPI.ScimFeatureSupport;
  bulk: AgentInsightAPI.BulkConfig;
  filter: AgentInsightAPI.FilterConfig;
  changePassword: AgentInsightAPI.ScimFeatureSupport;
  sort: AgentInsightAPI.ScimFeatureSupport;
  etag: AgentInsightAPI.ScimFeatureSupport;
  authenticationSchemes: AgentInsightAPI.AuthenticationScheme[];
  meta: AgentInsightAPI.ResourceMeta;
}
