/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface BlobStorageIntegrationResponse {
  id: string;
  projectId: string;
  type: AgentInsightAPI.BlobStorageIntegrationType;
  bucketName: string;
  endpoint: string | null;
  region: string;
  accessKeyId: string | null;
  prefix: string;
  exportFrequency: AgentInsightAPI.BlobStorageExportFrequency;
  enabled: boolean;
  forcePathStyle: boolean;
  fileType: AgentInsightAPI.BlobStorageIntegrationFileType;
  exportMode: AgentInsightAPI.BlobStorageExportMode;
  exportStartDate: string | null;
  compressed: boolean;
  nextSyncAt: string | null;
  lastSyncAt: string | null;
  lastError: string | null;
  lastErrorAt: string | null;
  createdAt: string;
  updatedAt: string;
}
