/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

/**
 * Collection of spans from a single instrumentation scope
 */
export interface OtelScopeSpan {
  /** Instrumentation scope information */
  scope?: AgentInsightAPI.OtelScope;
  /** Array of spans */
  spans?: AgentInsightAPI.OtelSpan[];
}
