/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type GetScoresResponseData =
  | AgentInsightAPI.GetScoresResponseData.Numeric
  | AgentInsightAPI.GetScoresResponseData.Categorical
  | AgentInsightAPI.GetScoresResponseData.Boolean
  | AgentInsightAPI.GetScoresResponseData.Correction
  | AgentInsightAPI.GetScoresResponseData.Text;

export namespace GetScoresResponseData {
  export interface Numeric extends AgentInsightAPI.GetScoresResponseDataNumeric {
    dataType: "NUMERIC";
  }

  export interface Categorical
    extends AgentInsightAPI.GetScoresResponseDataCategorical {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends AgentInsightAPI.GetScoresResponseDataBoolean {
    dataType: "BOOLEAN";
  }

  export interface Correction
    extends AgentInsightAPI.GetScoresResponseDataCorrection {
    dataType: "CORRECTION";
  }

  export interface Text extends AgentInsightAPI.GetScoresResponseDataText {
    dataType: "TEXT";
  }
}
