/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface GetScoresResponseDataText extends AgentInsightAPI.TextScore {
  trace?: AgentInsightAPI.GetScoresResponseTraceData;
}
