/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface CorrectionScore extends AgentInsightAPI.BaseScore {
  /** The numeric value of the score. Always 0 for correction scores. */
  value: number;
  /** The string representation of the correction content */
  stringValue: string;
}
