/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type ScoreV1 =
  /**
   * Score with NUMERIC data type */
  | AgentInsightAPI.ScoreV1.Numeric
  /**
   * Score with CATEGORICAL data type */
  | AgentInsightAPI.ScoreV1.Categorical
  /**
   * Score with BOOLEAN data type */
  | AgentInsightAPI.ScoreV1.Boolean
  /**
   * Score with TEXT data type */
  | AgentInsightAPI.ScoreV1.Text;

export namespace ScoreV1 {
  export interface Numeric extends AgentInsightAPI.NumericScoreV1 {
    dataType: "NUMERIC";
  }

  export interface Categorical extends AgentInsightAPI.CategoricalScoreV1 {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends AgentInsightAPI.BooleanScoreV1 {
    dataType: "BOOLEAN";
  }

  export interface Text extends AgentInsightAPI.TextScoreV1 {
    dataType: "TEXT";
  }
}
