/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type Score =
  /**
   * Score with NUMERIC data type */
  | AgentInsightAPI.Score.Numeric
  /**
   * Score with CATEGORICAL data type */
  | AgentInsightAPI.Score.Categorical
  /**
   * Score with BOOLEAN data type */
  | AgentInsightAPI.Score.Boolean
  /**
   * Score with CORRECTION data type */
  | AgentInsightAPI.Score.Correction
  /**
   * Score with TEXT data type */
  | AgentInsightAPI.Score.Text;

export namespace Score {
  export interface Numeric extends AgentInsightAPI.NumericScore {
    dataType: "NUMERIC";
  }

  export interface Categorical extends AgentInsightAPI.CategoricalScore {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends AgentInsightAPI.BooleanScore {
    dataType: "BOOLEAN";
  }

  export interface Correction extends AgentInsightAPI.CorrectionScore {
    dataType: "CORRECTION";
  }

  export interface Text extends AgentInsightAPI.TextScore {
    dataType: "TEXT";
  }
}
