/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface TextScore extends AgentInsightAPI.BaseScore {
  /** The text content of the score (1-500 characters) */
  stringValue: string;
}
