/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type Prompt = AgentInsightAPI.Prompt.Chat | AgentInsightAPI.Prompt.Text;

export namespace Prompt {
  export interface Chat extends AgentInsightAPI.ChatPrompt {
    type: "chat";
  }

  export interface Text extends AgentInsightAPI.TextPrompt {
    type: "text";
  }
}
