/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface PromptMetaListResponse {
  data: AgentInsightAPI.PromptMeta[];
  meta: AgentInsightAPI.utils.MetaResponse;
}
