/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../../../index.js";

export interface Observations {
  data: AgentInsightAPI.Observation[];
  meta: AgentInsightAPI.utils.MetaResponse;
}
