/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface CreateObservationEvent extends AgentInsightAPI.BaseEvent {
  body: AgentInsightAPI.ObservationBody;
}
