/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type IngestionEvent =
  /**
   * Creates a new trace. Upserts on id for updates if trace with id exists. */
  | AgentInsightAPI.IngestionEvent.TraceCreate
  /**
   * Creates a new score. Upserts on id for updates if score with id exists. */
  | AgentInsightAPI.IngestionEvent.ScoreCreate
  /**
   * Creates a new span. */
  | AgentInsightAPI.IngestionEvent.SpanCreate
  /**
   * Updates span based on id. */
  | AgentInsightAPI.IngestionEvent.SpanUpdate
  /**
   * Creates a new generation. */
  | AgentInsightAPI.IngestionEvent.GenerationCreate
  /**
   * Updates a generation based on id. */
  | AgentInsightAPI.IngestionEvent.GenerationUpdate
  /**
   * Creates an event. */
  | AgentInsightAPI.IngestionEvent.EventCreate
  /**
   * Langfuse SDKs only, used for debugging purposes. */
  | AgentInsightAPI.IngestionEvent.SdkLog
  /**
   * Deprecated event type */
  | AgentInsightAPI.IngestionEvent.ObservationCreate
  /**
   * Deprecated event type */
  | AgentInsightAPI.IngestionEvent.ObservationUpdate;

export namespace IngestionEvent {
  export interface TraceCreate extends AgentInsightAPI.TraceEvent {
    type: "trace-create";
  }

  export interface ScoreCreate extends AgentInsightAPI.ScoreEvent {
    type: "score-create";
  }

  export interface SpanCreate extends AgentInsightAPI.CreateSpanEvent {
    type: "span-create";
  }

  export interface SpanUpdate extends AgentInsightAPI.UpdateSpanEvent {
    type: "span-update";
  }

  export interface GenerationCreate extends AgentInsightAPI.CreateGenerationEvent {
    type: "generation-create";
  }

  export interface GenerationUpdate extends AgentInsightAPI.UpdateGenerationEvent {
    type: "generation-update";
  }

  export interface EventCreate extends AgentInsightAPI.CreateEventEvent {
    type: "event-create";
  }

  export interface SdkLog extends AgentInsightAPI.SdkLogEvent {
    type: "sdk-log";
  }

  export interface ObservationCreate
    extends AgentInsightAPI.CreateObservationEvent {
    type: "observation-create";
  }

  export interface ObservationUpdate
    extends AgentInsightAPI.UpdateObservationEvent {
    type: "observation-update";
  }
}
