/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface ObservationBody {
  id?: string;
  traceId?: string;
  type: AgentInsightAPI.ObservationType;
  name?: string;
  startTime?: string;
  endTime?: string;
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, AgentInsightAPI.MapValue>;
  input?: unknown;
  version?: string;
  metadata?: unknown;
  output?: unknown;
  usage?: AgentInsightAPI.Usage;
  level?: AgentInsightAPI.ObservationLevel;
  statusMessage?: string;
  parentObservationId?: string;
  environment?: string;
}
