/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export interface UpdateGenerationBody extends AgentInsightAPI.UpdateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, AgentInsightAPI.MapValue>;
  usage?: AgentInsightAPI.IngestionUsage;
  promptName?: string;
  usageDetails?: AgentInsightAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptVersion?: number;
}
