/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentInsightAPI from "../../../index.js";

export type UsageDetails =
  | Record<string, number>
  | AgentInsightAPI.OpenAiCompletionUsageSchema
  | AgentInsightAPI.OpenAiResponseUsageSchema;
